function Plot_Csys_vs_TOGW(x,y)
 
    figure('Color','w','Name','C_sys vs W_TOGW','NumberTitle','off');

    Axes = axes( ...
        'FontName', 'Arial', ...
        'FontSize', 12, ...
        'FontWeight', 'Bold', ...
        'NextPlot', 'Add', ...
        'XGrid', 'On', ...
        'YGrid', 'On', ...
        'Parent', gcf);

    title('C_{sys} vs W_{TOGW}', 'FontSize', 20);

    xlabel('W_{TOGW} (lbs)', 'FontSize', 16);
    ylabel('C_{sys} (lbs)', 'FontSize', 16);

    plot(x,y, ...
        'k.', ...
        'MarkerSize', 12, ...
        'Parent',Axes);

end


