function Plot_Istr_vs_Swet(x,y)
 
    figure('Color','w','Name','Istr vs S_wet','NumberTitle','off');

    Axes = axes( ...
        'FontName', 'Arial', ...
        'FontSize', 12, ...
        'FontWeight', 'Bold', ...
        'NextPlot', 'Add', ...
        'XGrid', 'On', ...
        'YGrid', 'On', ...
        'Parent', gcf);

    title('S_{wet} vs I_{str}', 'FontSize', 20);

    xlabel('S_{wet} (m^2)', 'FontSize', 16);
    ylabel('I_{str} (kg/m^2)', 'FontSize', 16);

    plot(x,y, ...
        'k.', ...
        'MarkerSize', 12, ...
        'Parent',Axes);

end


